import numpy as np
from enum import Enum

class BODY_PARTS_POSE_25(Enum):
    NOSE = 0
    NECK = 1
    RIGHT_SHOULDER = 2
    RIGHT_ELBOW = 3
    RIGHT_WRIST = 4
    LEFT_SHOULDER = 5
    LEFT_ELBOW = 6
    LEFT_WRIST = 7
    MID_HIP = 8
    RIGHT_HIP = 9
    RIGHT_KNEE = 10
    RIGHT_ANKLE = 11
    LEFT_HIP = 12
    LEFT_KNEE = 13
    LEFT_ANKLE = 14
    RIGHT_EYE = 15
    LEFT_EYE = 16
    RIGHT_EAR = 17
    LEFT_EAR = 18
    LEFT_FOOT = 19
    LEFT_TOE = 20
    LEFT_HEEL = 21
    RIGHT_FOOT = 22
    RIGHT_TOE = 23
    RIGHT_HEEL = 24
    LAST = 25

class BODY_PARTS_POSE_33(Enum):
    NOSE = 0
    LEFT_EYE_INNER =1
    LEFT_EYE =2
    LEFT_EYE_OUTER =3
    RIGHT_EYE_INNER =4
    RIGHT_EYE =5
    RIGHT_EYE_OUTER =6
    LEFT_EAR=7
    RIGHT_EAR=8
    LEFT_MOUSE=9
    RIGHT_MOUSE=10
    LEFT_SHOULDER=11
    RIGHT_SHOULDER=12
    LEFT_ELBOW=13
    RIGHT_ELBOW=14
    LEFT_WRIST=15
    RIGHT_WRIST=16
    LEFT_PINKY=17
    RIGHT_PINKY=18
    LEFT_INDEX=19
    RIGHT_INDEX=20
    LEFT_THUMB=21
    RIGHT_THUMB=22
    LEFT_HIP=23
    RIGHT_HIP=24
    LEFT_KNEE=25
    RIGHT_KNEE=26
    LEFT_ANKLE=27
    RIGHT_ANKLE=28
    LEFT_HEEL=29
    RIGHT_HEEL=30
    LEFT_TOE=31
    RIGHT_TOE=32

def convert_25_from_33(parts_33):
    parts_25 = np.zeros((25, 3))
    parts_25[BODY_PARTS_POSE_25.NOSE.value] = parts_33[BODY_PARTS_POSE_33.NOSE.value]
    parts_25[BODY_PARTS_POSE_25.NECK.value] = (parts_33[BODY_PARTS_POSE_33.RIGHT_SHOULDER.value] + parts_33[BODY_PARTS_POSE_33.LEFT_SHOULDER.value])/2
    parts_25[BODY_PARTS_POSE_25.RIGHT_SHOULDER.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_SHOULDER.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_ELBOW.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_ELBOW.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_WRIST.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_WRIST.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_SHOULDER.value] = parts_33[BODY_PARTS_POSE_33.LEFT_SHOULDER.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_ELBOW.value] = parts_33[BODY_PARTS_POSE_33.LEFT_ELBOW.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_WRIST.value] = parts_33[BODY_PARTS_POSE_33.LEFT_WRIST.value]
    parts_25[BODY_PARTS_POSE_25.MID_HIP.value] = (parts_33[BODY_PARTS_POSE_33.RIGHT_HIP.value] + parts_33[BODY_PARTS_POSE_33.LEFT_HIP.value])/2
    parts_25[BODY_PARTS_POSE_25.RIGHT_HIP.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_HIP.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_KNEE.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_KNEE.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_ANKLE.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_ANKLE.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_HIP.value] = parts_33[BODY_PARTS_POSE_33.LEFT_HIP.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_KNEE.value] = parts_33[BODY_PARTS_POSE_33.LEFT_KNEE.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_ANKLE.value] = parts_33[BODY_PARTS_POSE_33.LEFT_ANKLE.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_EYE.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_EYE.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_EYE.value] = parts_33[BODY_PARTS_POSE_33.LEFT_EYE.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_EAR.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_EAR.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_EAR.value] = parts_33[BODY_PARTS_POSE_33.LEFT_EAR.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_FOOT.value] = parts_33[BODY_PARTS_POSE_33.LEFT_TOE.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_TOE.value] = parts_33[BODY_PARTS_POSE_33.LEFT_TOE.value]
    parts_25[BODY_PARTS_POSE_25.LEFT_HEEL.value] = parts_33[BODY_PARTS_POSE_33.LEFT_HEEL.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_FOOT.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_TOE.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_TOE.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_TOE.value]
    parts_25[BODY_PARTS_POSE_25.RIGHT_HEEL.value] = parts_33[BODY_PARTS_POSE_33.RIGHT_HEEL.value]
    return parts_25