@startuml overview

component "skeleton_parser #1" as sp1 #LightYellow
component "skeleton_parser #2" as sp2 #LightYellow
component "skeleton_parser #3" as sp3 #LightYellow
component "skeleton_parser #4" as sp4 #LightYellow
component human_reconstructor #LightYellow
component web_server #pink

() "RGB-D Cam #1" as cam1 #LightYellow
() "RGB-D Cam #2" as cam2 #LightYellow
() "RGB-D Cam #3" as cam3 #LightYellow
() "RGB-D Cam #4" as cam4 #LightYellow
() "Display" as display #pink

cam1 -up-> sp1
sp1 -up-> human_reconstructor : UDP
cam2 -up-> sp2
sp2 -up-> human_reconstructor : UDP
cam3 -up-> sp3
sp3 -up-> human_reconstructor : UDP
cam4 -up-> sp4
sp4 -up-> human_reconstructor : UDP

human_reconstructor -up-> web_server : websocket
web_server -right-> display

@enduml
